/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * monitor.java
 *
 * Created on 8-feb-2011, 11.47.20
 */

package client;

import java.util.Observable;
import java.util.Observer;
import javax.swing.ImageIcon;

/**
 *
 * @author Fracido
 */
public class monitor extends javax.swing.JPanel implements Observer{

    /** Creates new form monitor */
    public monitor() {

        errorIcon = new ImageIcon(getClass().getResource("/client/resources/error.gif"));
        okIcon = new ImageIcon(getClass().getResource("/client/resources/ok.gif"));
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        routerstatus = new javax.swing.JLabel();
        jmsstatus = new javax.swing.JLabel();
        clientId = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        routerstatus.setIcon(errorIcon);
        routerstatus.setText("Router Status");

        jmsstatus.setIcon(errorIcon);
        jmsstatus.setText("JMS Status");

        clientId.setText("Client :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(routerstatus)
                    .addComponent(jmsstatus)
                    .addComponent(clientId))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clientId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(routerstatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmsstatus)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    ImageIcon errorIcon, okIcon;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clientId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jmsstatus;
    private javax.swing.JLabel routerstatus;
    // End of variables declaration//GEN-END:variables


    private ClientMessage msg;
    @Override
    public void update(Observable o, Object arg) {
        msg = (ClientMessage) arg;
        jTextArea1.append(msg.toString());
        
        if(msg.getJMSStatus() != null)
        	if(msg.getJMSStatus())
        		jmsstatus.setIcon(okIcon);
        	else
        		jmsstatus.setIcon(errorIcon);
        
        if(msg.getRouterStatus() != null)
        	if(msg.getRouterStatus())
        		routerstatus.setIcon(okIcon);
        	else
        		routerstatus.setIcon(errorIcon);

    }

    void setClientId(String string) {
        clientId.setText("Client: "+string);
    }

}
